Disable Ruby bindings
Currently the build breaks with:

/builddir/build/BUILD/openbabel-3.1.1/scripts/ruby/openbabel-ruby.cpp: In function 'void SWIG_RubyInitializeTrackings()':
/builddir/build/BUILD/openbabel-3.1.1/scripts/ruby/openbabel-ruby.cpp:1263:85: error: call of overloaded 'rb_define_virtual_variable(const char [21], VALUE (&)(...), NULL)' is ambiguous
 1263 |   rb_define_virtual_variable("SWIG_TRACKINGS_COUNT", swig_ruby_trackings_count, NULL);
      |

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>